export const phrases = [
  // love → present
  {
    id: "1",
    russian: "Я люблю",
    english: "I love",
    tense: "present",
    person: "I",
  },
  {
    id: "2",
    russian: "Ты любишь",
    english: "You love",
    tense: "present",
    person: "You",
  },
  {
    id: "3",
    russian: "Он любит",
    english: "He loves",
    tense: "present",
    person: "He",
  },
  {
    id: "4",
    russian: "Она любит",
    english: "She loves",
    tense: "present",
    person: "She",
  },
  {
    id: "5",
    russian: "Мы любим",
    english: "We love",
    tense: "present",
    person: "We",
  },
  {
    id: "6",
    russian: "Они любят",
    english: "They love",
    tense: "present",
    person: "They",
  },

  // love → past
  {
    id: "7",
    russian: "Я любил",
    english: "I loved",
    tense: "past",
    person: "I",
  },
  {
    id: "8",
    russian: "Ты любил",
    english: "You loved",
    tense: "past",
    person: "You",
  },
  {
    id: "9",
    russian: "Он любил",
    english: "He loved",
    tense: "past",
    person: "He",
  },
  {
    id: "10",
    russian: "Она любила",
    english: "She loved",
    tense: "past",
    person: "She",
  },
  {
    id: "11",
    russian: "Мы любили",
    english: "We loved",
    tense: "past",
    person: "We",
  },
  {
    id: "12",
    russian: "Они любили",
    english: "They loved",
    tense: "past",
    person: "They",
  },

  // love → future
  {
    id: "13",
    russian: "Я буду любить",
    english: "I will love",
    tense: "future",
    person: "I",
  },
  {
    id: "14",
    russian: "Ты будешь любить",
    english: "You will love",
    tense: "future",
    person: "You",
  },
  {
    id: "15",
    russian: "Он будет любить",
    english: "He will love",
    tense: "future",
    person: "He",
  },
  {
    id: "16",
    russian: "Она будет любить",
    english: "She will love",
    tense: "future",
    person: "She",
  },
  {
    id: "17",
    russian: "Мы будем любить",
    english: "We will love",
    tense: "future",
    person: "We",
  },
  {
    id: "18",
    russian: "Они будут любить",
    english: "They will love",
    tense: "future",
    person: "They",
  },
];
